---
core:
    num_workers: 10


inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "/home/ipvzero/Ping/hosts.yaml"
        group_file: "/home/ipvzero/Ping/groups.yaml"
        defaults_file: "/home/ipvzero/Ping/defaults.yaml"
