---


R1:
    hostname: 192.168.31.11
    platform: 'ios'
    username: john
    password: cisco
    groups:
        - cisco_group


R2:
    hostname: 192.168.31.12
    platform: 'ios'
    username: john
    password: cisco
    groups:
        - cisco_group





R4:
    hostname: 192.168.31.14
    platform: 'ios'
    username: john
    password: cisco
    groups:
        - cisco_group


R5:
    hostname: 192.168.31.15
    platform: 'ios'
    username: john
    password: cisco
    groups:
        - cisco_group



R6:
    hostname: 192.168.31.16
    platform: 'ios'
    username: john
    password: cisco
    groups:
        - cisco_group



R7:
    hostname: 192.168.31.17
    platform: 'ios'
    username: john
    password: cisco
    groups:
        - cisco_group



R8:
    hostname: 192.168.31.18
    platform: 'ios'
    username: john
    password: cisco
    groups:
        - cisco_group
